/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DemoContainer: typeof import('./../../apps/docs/.vitepress/theme/components/DemoContainer.vue')['default']
    FunctionInfo: typeof import('./../../apps/docs/.vitepress/theme/components/FunctionInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
