// ─── PlayerId ─────────────────────────────────────────────────────────────────
// Merged from all MagicPlayer test files

export enum PlayerId {
  // api.test.ts
  ApiShape = 'api-shape',
  ApiObjects = 'api-objects',
  ApiVidM = 'api-vid-m',
  ApiAudM = 'api-aud-m',
  ApiVPlay = 'api-v-play',
  ApiVPause = 'api-v-pause',
  ApiVToggle = 'api-v-toggle',
  ApiVMute = 'api-v-mute',
  ApiVUnmute = 'api-v-unmute',
  ApiVSeek = 'api-v-seek',
  ApiAPlay = 'api-a-play',
  ApiAPause = 'api-a-pause',
  ApiAMute = 'api-a-mute',
  ApiDefaults = 'api-defaults',
  ApiVolDefault = 'api-vol-default',
  ApiCtDefault = 'api-ct-default',
  ApiDurDefault = 'api-dur-default',
  ApiMediaLoad = 'api-media-load',
  // edge-cases.test.ts
  EdgeMulti1 = 'edge-multi-1',
  EdgeMulti2 = 'edge-multi-2',
  EdgeRapid = 'edge-rapid',
  EdgeNoControls = 'edge-no-controls',
  EdgeShared = 'edge-shared',
  EdgeDisplayTime = 'edge-display-time',
  EdgeUnmount = 'edge-unmount',
  EdgeExplicitId = 'edge-explicit-id',
  EdgeDataMute = 'edge-data-mute',
  EdgeDataPlay = 'edge-data-play',
  EdgeVideoSrc = 'edge-video-src',
  // events.test.ts
  EvtPlay = 'evt-play',
  EvtPause = 'evt-pause',
  EvtStart = 'evt-start',
  EvtMute = 'evt-mute',
  EvtUnmute = 'evt-unmute',
  EvtTouch = 'evt-touch',
  // interactions.test.ts
  IntPlayBtn = 'int-play-btn',
  IntToggleBtn = 'int-toggle-btn',
  IntMuteBtn = 'int-mute-btn',
  IntOverlayRender = 'int-overlay-render',
  IntProviderTouch = 'int-provider-touch',
  IntStandaloneVisible = 'int-standalone-visible',
  IntTimelineDrag = 'int-timeline-drag',
  IntTimelineDragend = 'int-timeline-dragend',
  IntVideoEl = 'int-video-el',
  IntMediaStart = 'int-media-start',
  // options.test.ts
  OptModeDefault = 'opt-mode-default',
  OptAudioMode = 'opt-audio-mode',
  OptPosterVisible = 'opt-poster-visible',
  OptPosterHide = 'opt-poster-hide',
  OptPosterLoadedOnly = 'opt-poster-loaded-only',
  OptStandalone = 'opt-standalone',
  OptNonStandalone = 'opt-non-standalone',
  OptHasOverlay = 'opt-has-overlay',
  OptPlaybackFalse = 'opt-playback-false',
  OptPreloadAuto = 'opt-preload-auto',
  // rendering.test.ts
  RenderProvider = 'render-provider',
  RenderDataId = 'render-data-id',
  RenderModeVideo = 'render-mode-video',
  RenderModeAudio = 'render-mode-audio',
  RenderDefaults = 'render-defaults',
  RenderSlot = 'render-slot',
  RenderVideoEl = 'render-video-el',
  RenderVideoInline = 'render-video-inline',
  RenderVideoPreload = 'render-video-preload',
  RenderAudioEl = 'render-audio-el',
  RenderOverlay = 'render-overlay',
  RenderOverlayAttrs = 'render-overlay-attrs',
  RenderPoster = 'render-poster',
  RenderPosterVisible = 'render-poster-visible',
  RenderPosterSlot = 'render-poster-slot',
  RenderVc = 'render-vc',
  RenderVcAttrs = 'render-vc-attrs',
  RenderVcStandalone = 'render-vc-standalone',
  RenderVcBar = 'render-vc-bar',
  RenderVcTimeline = 'render-vc-timeline',
  RenderAc = 'render-ac',
  RenderAcAttrs = 'render-ac-attrs',
  RenderAcSlots = 'render-ac-slots',
  RenderTl = 'render-tl',
}

// ─── TestId ───────────────────────────────────────────────────────────────────

export enum TestId {
  // api.test.ts
  Play = 'play',
  Pause = 'pause',
  Toggle = 'toggle',
  Mute = 'mute',
  Unmute = 'unmute',
  Seek10 = 'seek-10',
  Playing = 'playing',
  Paused = 'paused',
  Muted = 'muted',
  Started = 'started',
  Loaded = 'loaded',
  Fullscreen = 'fullscreen',
  Volume = 'volume',
  Duration = 'duration',
  CurrentTime = 'current-time',
  // edge-cases.test.ts
  Play1 = 'play-1',
  Play2 = 'play-2',
  Playing1 = 'playing-1',
  Playing2 = 'playing-2',
  Child = 'child',
  // events.test.ts
  Events = 'events',
  // interactions.test.ts
  Touched = 'touched',
  Dragging = 'dragging',
  PlayBtn = 'play-btn',
  PauseBtn = 'pause-btn',
  ToggleBtn = 'toggle-btn',
  MuteBtn = 'mute-btn',
  // options.test.ts
  Poster = 'poster',
  // rendering.test.ts
  PosterContent = 'poster-content',
}
