/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMaasChevronE500: typeof import('~icons/maas/chevron-e500')['default']
    IMaasSignInfoOval500: typeof import('~icons/maas/sign-info-oval500')['default']
  }
}
