packages:
  - packages/*
  - apps/*
  - packages/nuxt/playground
  - '!packages/nuxt/test'
catalog:
  '@floating-ui/vue': ^1.1.7
  '@maas/magic-timer': ^1.2.0
  '@maas/mirror': ^1.0.0-beta.9
  '@maas/vue-primitive': ^1.3.0
  '@nuxt/kit': ^3.17.6
  '@tailwindcss/vite': ^4.1.11
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.16.0
  '@vueuse/core': '>=13.5.0'
  '@vueuse/integrations': '>=13.5.0'
  defu: ^6.1.4
  esno: ^4.8.0
  focus-trap: ^7.6.5
  fs-extra: ^11.3.0
  hls.js: ^1.6.6
  luxon: ^3.6.1
  mitt: ^3.0.1
  tailwindcss: ^4.1.11
  motion: ^12.23.0
  nuxt: ^3.17.6
  prettier: ^3.6.2
  tsup: ^8.5.0
  typescript: 5.6.3
  universal-cookie: ^7.2.2
  vue: ^3.5.17
