packages:
  - packages/*
  - apps/*
  - packages/nuxt/playground
  - '!packages/nuxt/test'
catalog:
  '@floating-ui/vue': ^1.1.6
  '@maas/magic-timer': ^1.1.1
  '@maas/mirror': ^0.12.2
  '@maas/vue-primitive': ^1.2.1
  '@nuxt/kit': ^3.16.2
  '@nuxt/schema': ^3.16.2
  '@nuxtjs/tailwindcss': ^6.13.2
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.14.0
  '@vueuse/core': '>=13.0.0'
  '@vueuse/integrations': '>=13.0.0'
  defu: ^6.1.4
  esno: ^4.8.0
  focus-trap: ^7.6.4
  fs-extra: ^11.3.0
  hls.js: ^1.6.0
  luxon: ^3.6.1
  mitt: ^3.0.1
  tailwindcss: 3.4.17
  motion: ^12.6.3
  nuxt: ^3.16.2
  tsup: ^8.4.0
  typescript: 5.6.3
  universal-cookie: ^7.2.2
  vue: ^3.5.13
