packages:
  - packages/*
  - apps/*
  - packages/nuxt/playground
  - '!packages/nuxt/test'

catalog:
  '@floating-ui/vue': ^1.1.7
  '@maas/magic-timer': ^1.2.0
  '@maas/mirror': ^0.16.0
  '@maas/vue-primitive': ^1.3.0
  '@nuxt/kit': ^4.0.1
  '@nuxtjs/tailwindcss': ^6.14.0
  '@types/fs-extra': ^11.0.4
  '@types/node': ^24.1.0
  '@vueuse/core': '>=13.5.0'
  '@vueuse/integrations': '>=13.5.0'
  defu: ^6.1.4
  esno: ^4.8.0
  focus-trap: ^7.6.5
  fs-extra: ^11.3.0
  hls.js: ^1.6.7
  luxon: ^3.7.1
  mitt: ^3.0.1
  motion: ^12.23.9
  nuxt: ^4.0.1
  prettier: ^3.6.2
  tailwindcss: 3.4.17
  tsup: ^8.5.0
  typescript: 5.6.3
  universal-cookie: ^8.0.1
  vue: ^3.5.18
