packages:
  - packages/*
  - apps/*
  - packages/nuxt/playground
  - '!packages/nuxt/test'
catalog:
  '@floating-ui/vue': ^1.1.6
  '@maas/magic-timer': ^1.1.1
  '@maas/mirror': ^0.12.2
  '@maas/vue-primitive': ^1.1.0
  '@nuxt/kit': ^3.15.4
  '@nuxt/schema': ^3.15.4
  '@nuxtjs/tailwindcss': ^6.13.1
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.13.4
  '@vueuse/core': '>=12.7.0'
  '@vueuse/integrations': '>=12.7.0'
  defu: ^6.1.4
  esno: ^4.8.0
  focus-trap: ^7.6.4
  fs-extra: ^11.3.0
  hls.js: ^1.5.20
  luxon: ^3.5.0
  mitt: ^3.0.1
  tailwindcss: 4.0.9
  motion: ^12.4.4
  nuxt: ^3.15.4
  tsup: ^8.3.6
  typescript: 5.8.2
  universal-cookie: ^7.2.2
  vue: ^3.5.13
