/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMaasBrandFigma500: typeof import('~icons/maas/brand-figma500')['default']
    IMaasBrandGithub500: typeof import('~icons/maas/brand-github500')['default']
    IMaasBrandNuxt500: typeof import('~icons/maas/brand-nuxt500')['default']
    IMaasBrandVue500: typeof import('~icons/maas/brand-vue500')['default']
    IMaasChevronE500: typeof import('~icons/maas/chevron-e500')['default']
    IMaasEditAlt500: typeof import('~icons/maas/edit-alt500')['default']
    IMaasMaasAz500: typeof import('~icons/maas/maas-az500')['default']
    IMaasMaasDt500: typeof import('~icons/maas/maas-dt500')['default']
    IMaasMaasMr500: typeof import('~icons/maas/maas-mr500')['default']
    IMaasMaasOf500: typeof import('~icons/maas/maas-of500')['default']
    IMaasMaasRobot500: typeof import('~icons/maas/maas-robot500')['default']
    IMaasMaasVe500: typeof import('~icons/maas/maas-ve500')['default']
    IMaasSignInfoOval500: typeof import('~icons/maas/sign-info-oval500')['default']
  }
}
