/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMaasBrandFigma500: typeof import('~icons/maas/brand-figma500')['default']
    IMaasBrandGithub500: typeof import('~icons/maas/brand-github500')['default']
    IMaasBrandNuxt500: typeof import('~icons/maas/brand-nuxt500')['default']
    IMaasBrandVue500: typeof import('~icons/maas/brand-vue500')['default']
    IMaasCarabiner500: typeof import('~icons/maas/carabiner500')['default']
    IMaasCheck500: typeof import('~icons/maas/check500')['default']
    IMaasChevronE500: typeof import('~icons/maas/chevron-e500')['default']
    IMaasChevronN500: typeof import('~icons/maas/chevron-n500')['default']
    IMaasChevronS500: typeof import('~icons/maas/chevron-s500')['default']
    IMaasChevronW500: typeof import('~icons/maas/chevron-w500')['default']
    IMaasCircle500: typeof import('~icons/maas/circle500')['default']
    IMaasClose500: typeof import('~icons/maas/close500')['default']
    IMaasCloseOval500: typeof import('~icons/maas/close-oval500')['default']
    IMaasDrawerBottom500: typeof import('~icons/maas/drawer-bottom500')['default']
    IMaasEditAlt500: typeof import('~icons/maas/edit-alt500')['default']
    IMaasMaasAz500: typeof import('~icons/maas/maas-az500')['default']
    IMaasMaasCircle500: typeof import('~icons/maas/maas-circle500')['default']
    IMaasMaasDt500: typeof import('~icons/maas/maas-dt500')['default']
    IMaasMaasMr500: typeof import('~icons/maas/maas-mr500')['default']
    IMaasMaasObotSticker500: typeof import('~icons/maas/maas-obot-sticker500')['default']
    IMaasMaasOf500: typeof import('~icons/maas/maas-of500')['default']
    IMaasMaasRobot500: typeof import('~icons/maas/maas-robot500')['default']
    IMaasMaasRobotSticker500: typeof import('~icons/maas/maas-robot-sticker500')['default']
    IMaasMaasVe500: typeof import('~icons/maas/maas-ve500')['default']
    IMaasMenu500: typeof import('~icons/maas/menu500')['default']
    IMaasMoon: typeof import('~icons/maas/moon')['default']
    IMaasMoon500: typeof import('~icons/maas/moon500')['default']
    IMaasRmaasObotSticker500: typeof import('~icons/maas/rmaas-obot-sticker500')['default']
    IMaasRobot500: typeof import('~icons/maas/robot500')['default']
    IMaasRobotSticker500: typeof import('~icons/maas/robot-sticker500')['default']
    IMaasSignInfoOval500: typeof import('~icons/maas/sign-info-oval500')['default']
    IMaasSpacer500: typeof import('~icons/maas/spacer500')['default']
    IMaasSun500: typeof import('~icons/maas/sun500')['default']
    IMaasVe500: typeof import('~icons/maas/ve500')['default']
  }
}
