export enum CommandId {
  DataId = 'r-data-id',
  RenderSlot = 'r-slot',
  ViewId = 'r-view-id',
  ViewSlot = 'r-view-slot',
  TriggerAttrs = 'r-trigger-attrs',
  Item = 'r-item',
  ItemDisabled = 'r-item-disabled',
  ContentClosed = 'r-content-closed',
  ContentOpen = 'r-content-open',
  ApiShape = 'api-shape',
  ApiOpen = 'api-open',
  ApiInitial = 'api-initial',
  ApiClose = 'api-close',
  ApiSv = 'api-sv',
  Trigger = 'int-trigger',
  Hover = 'int-hover',
  Click = 'int-click',
  Initial = 'int-initial',
  CloseApi = 'int-close-api',
  Escape = 'kb-esc',
  ArrowDown = 'kb-arrow-down',
  ArrowCycle = 'kb-arrow-cycle',
  ArrowUp = 'kb-arrow-up',
  NoKey = 'opt-no-key',
  InitialView = 'opt-initial-view',
  NoLoop = 'opt-no-loop',
  Multi1 = 'edge-multi-1',
  Multi2 = 'edge-multi-2',
  Cycle = 'edge-cycle',
  Disabled = 'edge-disabled',
  Nested = 'edge-nested',
  EdgeSlot = 'edge-slot',
  ModalDefault = 'md-modal-default',
  ModalSync = 'md-modal-sync',
  ModalSyncClose = 'md-modal-sync-close',
  ModalAfterLeave = 'md-modal-after-leave',
  ModalLayout = 'md-modal-layout',
  DrawerDefault = 'md-drawer-default',
  DrawerSync = 'md-drawer-sync',
  DrawerSyncClose = 'md-drawer-sync-close',
  DrawerAfterLeave = 'md-drawer-after-leave',
  DrawerLayout = 'md-drawer-layout',
}

export enum ViewId {
  V0 = 'v0',
  MyView = 'my-view',
  MainView = 'main-view',
  ViewA = 'view-a',
  ViewB = 'view-b',
  NonInitial = 'non-initial',
  TheInitial = 'the-initial',
  ParentView = 'parent-view',
  ChildView = 'child-view',
}

export enum ItemId {
  Item1 = 'item-1',
  DItem = 'd-item',
  Item2 = 'item-2',
  ClickItem = 'click-item',
  First = 'first',
  Second = 'second',
  KbItem1 = 'kb-item-1',
  KbItem2 = 'kb-item-2',
  KbItem3 = 'kb-item-3',
  LItem1 = 'l-item-1',
  LItem2 = 'l-item-2',
  Enabled = 'enabled',
  Disabled = 'disabled',
  ParentItem = 'parent-item',
  ChildItem = 'child-item',
  SItem = 's-item',
}

export enum TestId {
  Child = 'child',
  Active = 'active',
  Open = 'open',
  Close = 'close',
  View = 'view',
  SelectB = 'select-b',
  Trigger = 'trigger',
  Active1 = 'active-1',
  Active2 = 'active-2',
  Open1 = 'open-1',
  SlotActive = 'slot-active',
  SlotDisabled = 'slot-disabled',
  LayoutContent = 'layout-content',
}
