export enum ModalId {
  // rendering
  RenderTrigger = 'render-trigger',
  RenderTriggerActive = 'render-trigger-active',
  RenderTriggerDisabled = 'render-trigger-disabled',
  RenderTriggerOpen = 'render-trigger-open',
  RenderContentClosed = 'render-content-closed',
  RenderContentOpen = 'render-content-open',
  RenderDataId = 'render-data-id',
  RenderAriaModal = 'render-aria-modal',
  RenderTag = 'render-tag',
  RenderSlot = 'render-slot',
  RenderBackdrop = 'render-backdrop',
  // interactions
  Interact = 'interact',
  InteractToggle = 'interact-toggle',
  InteractDisabled = 'interact-disabled',
  InteractContent = 'interact-content',
  Key = 'key',
  KeyDisabled = 'key-disabled',
  // api
  ApiOpen = 'api-open',
  ApiClose = 'api-close',
  ApiInitial = 'api-initial',
  ApiReflect = 'api-reflect',
  Multi1 = 'multi-1',
  Multi2 = 'multi-2',
  // options
  OptTagDialog = 'opt-tag-dialog',
  OptTagDiv = 'opt-tag-div',
  OptTeleportBody = 'opt-teleport-body',
  OptTeleportCustom = 'opt-teleport-custom',
  OptTeleportDisabled = 'opt-teleport-disabled',
  OptKeyDefault = 'opt-key-default',
  OptKeyDisabled = 'opt-key-disabled',
  OptScroll = 'opt-scroll',
  OptScrollFalse = 'opt-scroll-false',
  OptTransition = 'opt-transition',
  OptFocusFalse = 'opt-focus-false',
  ReactivityTag = 'opt-reactivity-tag',
  // events
  EventOpen = 'event-open',
  EventClose = 'event-close',
  EventOrder = 'event-order',
  EventLeaveOrder = 'event-leave-order',
  EventPayload = 'event-payload',
  // edge cases
  Default = 'default',
  Rapid = 'rapid',
  DoubleOpen = 'double-open',
  DoubleClose = 'double-close',
  Unmount = 'unmount',
  CleanupScroll = 'cleanup-scroll',
  Concurrent1 = 'concurrent-1',
  Concurrent2 = 'concurrent-2',
  Concurrent3 = 'concurrent-3',
}

export enum TestId {
  Trigger = 'trigger',
  CloseBtn = 'close-btn',
  IsActive = 'is-active',
  ModalContent = 'modal-content',
  Open1 = 'open-1',
  Open2 = 'open-2',
  Active1 = 'active-1',
  Active2 = 'active-2',
  Active3 = 'active-3',
  RapidBtn = 'rapid-btn',
  DoubleOpenBtn = 'double-open-btn',
  DoubleCloseBtn = 'double-close-btn',
  ToggleBtn = 'toggle-btn',
  OpenAll = 'open-all',
  ClearEvents = 'clear-events',
  Events = 'events',
  LastPayload = 'last-payload',
}
