export enum DrawerId {
  // rendering
  RenderTrigger = 'render-trigger',
  RenderTriggerActive = 'render-trigger-active',
  RenderTriggerDisabled = 'render-trigger-disabled',
  RenderTriggerOpen = 'render-trigger-open',
  RenderContentClosed = 'render-content-closed',
  RenderContentOpen = 'render-content-open',
  RenderDataId = 'render-data-id',
  RenderPosition = 'render-position',
  RenderAriaModal = 'render-aria-modal',
  RenderTag = 'render-tag',
  RenderSlot = 'render-slot',
  RenderBackdrop = 'render-backdrop',
  RenderDisabled = 'render-disabled',
  RenderDragging = 'render-dragging',
  // interactions
  Interact = 'interact',
  InteractToggle = 'interact-toggle',
  InteractContent = 'interact-content',
  InteractDrag = 'interact-drag',
  InteractDragged = 'interact-dragged',
  InteractDisabledDrag = 'interact-disabled-drag',
  PreventDragClose = 'prevent-drag-close',
  Key = 'key',
  KeyDisabled = 'key-disabled',
  Disabled = 'disabled',
  // api
  ApiDrawer = 'api-drawer',
  ApiClose = 'api-close',
  ApiCycle = 'api-cycle',
  Drawer1 = 'drawer-1',
  Drawer2 = 'drawer-2',
  InitialDrawer = 'initial-drawer',
  NoTransitionDrawer = 'no-transition-drawer',
  SnapDrawer = 'snap-drawer',
  // options
  PositionTop = 'position-top',
  PositionRight = 'position-right',
  PositionBottom = 'position-bottom',
  PositionLeft = 'position-left',
  OptTagDialog = 'opt-tag-dialog',
  OptTagDiv = 'opt-tag-div',
  TeleportDisabled = 'teleport-disabled',
  TeleportCustom = 'teleport-custom',
  DisabledTrue = 'disabled-true',
  DisabledFalse = 'disabled-false',
  SnapPercent = 'snap-percent',
  SnapPx = 'snap-px',
  SnapMixed = 'snap-mixed',
  ScrollLock = 'scroll-lock',
  NoScrollLock = 'no-scroll-lock',
  CustomTransition = 'custom-transition',
  InitialOpen = 'initial-open',
  InitialClosed = 'initial-closed',
  InitialNoAnim = 'initial-no-anim',
  NoWheel = 'no-wheel',
  ReactivityDisabled = 'opt-reactivity-disabled',
  CustomEasing = 'opt-custom-easing',
  // events
  EventOpen = 'event-open',
  EventClose = 'event-close',
  EventOrder = 'event-order',
  EventLeaveOrder = 'event-leave-order',
  EventPayload = 'event-payload',
  EventDrag = 'event-drag',
  EventDragPayload = 'event-drag-payload',
  EventAfterDrag = 'event-after-drag',
  // edge cases
  Default = 'default',
  WarnSnap = 'warn-snap',
  OvershootWarn = 'overshoot-warn',
  RapidDrawer = 'rapid',
  DoubleOpen = 'double-open',
  DoubleClose = 'double-close',
  UnmountDrawer = 'unmount',
  CleanupScroll = 'cleanup-scroll',
  OvershootPx = 'overshoot-px',
  OvershootRem = 'overshoot-rem',
  Concurrent1 = 'concurrent-1',
  Concurrent2 = 'concurrent-2',
  Concurrent3 = 'concurrent-3',
}

export enum TestId {
  Trigger = 'trigger',
  CloseBtn = 'close-btn',
  IsActive = 'is-active',
  DrawerContent = 'drawer-content',
  ProgressX = 'progress-x',
  ProgressY = 'progress-y',
  Open1 = 'open-1',
  Open2 = 'open-2',
  Active1 = 'active-1',
  Active2 = 'active-2',
  Active3 = 'active-3',
  SnapBtn = 'snap-btn',
  RapidBtn = 'rapid-btn',
  DoubleOpenBtn = 'double-open-btn',
  DoubleCloseBtn = 'double-close-btn',
  ToggleBtn = 'toggle-btn',
  OpenAll = 'open-all',
  ClearEvents = 'clear-events',
  Events = 'events',
  LastPayload = 'last-payload',
}
