export enum TrayId {
  // rendering
  RenderInline = 'render-inline',
  RenderHandles = 'render-handles',
  RenderNoHandles = 'render-no-handles',
  RenderPartialHandles = 'render-partial-handles',
  RenderDisabled = 'render-disabled',
  // slots
  SlotHandleGeneric = 'slot-handle-generic',
  SlotHandlePerSide = 'slot-handle-per-side',
  SlotHandleFallback = 'slot-handle-fallback',
  // api
  ApiSnap = 'api-snap',
  // interactions
  Overshoot = 'overshoot',
  // events
  EventSnap = 'event-snap',
  EventMagnetism = 'event-magnetism',
  // options
  OptTagDiv = 'opt-tag-div',
  OptTagDialog = 'opt-tag-dialog',
  OptInsetTrue = 'opt-inset-true',
  OptInsetFalse = 'opt-inset-false',
  OptSideTop = 'opt-side-top',
  OptSideRight = 'opt-side-right',
  OptSideLeft = 'opt-side-left',
  OptSnapPx = 'opt-snap-px',
  OptHandlesObject = 'opt-handles-object',
  OptDisabledDrag = 'opt-disabled-drag',
  OptDisabledReactive = 'opt-disabled-reactive',
  OptInitialSnap = 'opt-initial-snap',
  OptInitialTransition = 'opt-initial-transition',
  OptCustomEasing = 'opt-custom-easing',
  OptThresholdHigh = 'opt-threshold-high',
  OptThresholdDirUp = 'opt-threshold-dir-up',
  OptThresholdDirDown = 'opt-threshold-dir-down',
  OptSnapModeStep = 'opt-snap-mode-step',
  OptSnapModeClosest = 'opt-snap-mode-closest',
  // magnetism
  MagneticLeft = 'magnetic-left',
  MagneticInner = 'magnetic-inner',
  MagneticOuter = 'magnetic-outer',
  MagneticBoth = 'magnetic-both',
  MagneticSettle = 'magnetic-settle',
  MagneticEased = 'magnetic-eased',
  MagneticLinear = 'magnetic-linear',
  MagneticHold = 'magnetic-hold',
  MagneticDeep = 'magnetic-deep',
  MagneticGate = 'magnetic-gate',
  MagneticNoJump = 'magnetic-no-jump',
  MagneticDisabled = 'magnetic-disabled',
  MagneticInvalid = 'magnetic-invalid',
  // edge cases
  EdgeDefault = 'edge-default',
  EdgeWarnNoZero = 'edge-warn-no-zero',
  EdgeNoWarnZero = 'edge-no-warn-zero',
  EdgeSnapNoPoints = 'edge-snap-no-points',
  EdgeOvershootInvalid = 'edge-overshoot-invalid',
  EdgeOvershootRem = 'edge-overshoot-rem',
  EdgeConcurrent1 = 'edge-concurrent-1',
  EdgeConcurrent2 = 'edge-concurrent-2',
  EdgeConcurrent3 = 'edge-concurrent-3',
  EdgeUnmount = 'edge-unmount',
  EdgeDisabledDuringDrag = 'edge-disabled-during-drag',
  EdgeRapidSnap = 'edge-rapid-snap',
}

export enum TestId {
  Content = 'content',
  SnapBtn = 'snap-btn',
  ProgressBottom = 'progress-bottom',
  ProgressRight = 'progress-right',
  ProgressTop = 'progress-top',
  ProgressLeft = 'progress-left',
  DraggedBottom = 'dragged-bottom',
  Events = 'events',
  Active1 = 'active-1',
  Active2 = 'active-2',
  Active3 = 'active-3',
  SnapAll = 'snap-all',
  ToggleBtn = 'toggle-btn',
  DisableBtn = 'disable-btn',
  RapidBtn = 'rapid-btn',
}
