export enum DraggableId {
  Shape = 'api-shape',
  Snap = 'api-snap',
  SnapAnim = 'api-snap-anim',
  PDown = 'int-pdown',
  Move = 'int-move',
  IntDisabled = 'int-disabled',
  DataId = 'render-data-id',
  RenderSlot = 'render-slot',
  RenderTagDiv = 'render-tag-div',
  RenderTagDialog = 'render-tag-dialog',
  Dragging = 'render-dragging',
  NotDisabled = 'render-not-disabled',
  RenderDisabled = 'render-disabled',
  RenderSnap = 'render-snap',
  OptDisabled = 'opt-disabled',
  Initial = 'opt-initial',
  DefaultSnap = 'opt-default-snap',
  CustomSnaps = 'opt-custom-snaps',
  OptTagDiv = 'opt-tag-div',
  OptTagDialog = 'opt-tag-dialog',
  ReactivityDisabled = 'opt-reactivity-disabled',
  SnapPayload = 'ev-snap-payload',
  BeforeSnap = 'ev-before-snap',
  AfterSnap = 'ev-after-snap',
  DragPayload = 'ev-drag-payload',
  Offset = 'ev-offset',
  Multi1 = 'edge-multi-1',
  Multi2 = 'edge-multi-2',
  Cycle = 'edge-cycle',
  Overlay = 'edge-overlay',
  Transform = 'edge-transform',
}

export enum TestId {
  Snap = 'snap',
  Snap1 = 'snap1',
  Tl = 'tl',
  Br = 'br',
  C = 'c',
}
