export enum CarouselId {
  ApiShape = 'api-shape',
  ApiSlideCount = 'api-slide-count',
  ApiSnapTo = 'api-snap-to',
  ApiNext = 'api-next',
  ApiPrevious = 'api-previous',
  OptDefaults = 'opt-defaults',
  OptLoop = 'opt-loop',
  OptMerge = 'opt-merge',
  RenderProvider = 'render-provider',
  RenderSlides = 'render-slides',
  RenderActive = 'render-active',
  RenderTrigger = 'render-trigger',
  StateShared = 'state-shared',
  StateInd1 = 'state-ind-1',
  StateInd2 = 'state-ind-2',
  InteractionDraggable = 'interaction-draggable',
  InteractionDrag = 'interaction-drag',
  InteractionRubberband = 'interaction-rubberband',
  EventsSnapTo = 'events-snap-to',
  EventsDrag = 'events-drag',
}

export enum TestId {
  View = 'view',
  Slide = 'slide',
  ActiveIndex = 'active-index',
  SlideCount = 'slide-count',
  Progress = 'progress',
  Next = 'next',
  Previous = 'previous',
  SnapTo = 'snap-to',
  TriggerNext = 'trigger-next',
  TriggerPrevious = 'trigger-previous',
}
