export * from './src/functions/clampValue'
export * from './src/functions/easings'
export * from './src/functions/formatTime'
export * from './src/functions/interpolate'
export * from './src/functions/isIOS'
export * from './src/functions/isWithinRange'
export * from './src/functions/mapValue'
export * from './src/functions/matchClass'
export * from './src/functions/pointerCapture'
export * from './src/functions/scrollbarGutterSupport'
export * from './src/functions/scrollbarWidth'
export * from './src/functions/slugify'
export * from './src/functions/uniq'

export type * from './src/types'
