export enum MenuId {
  ApiShape = 'api-shape',
  ApiChannel = 'api-channel',
  ApiSelect = 'api-select',
  ApiUnselect = 'api-unselect',
  ApiChSelect = 'api-ch-select',
  EdgeNested = 'edge-nested',
  EdgeMulti1 = 'edge-multi-1',
  EdgeMulti2 = 'edge-multi-2',
  EdgeUnmount = 'edge-unmount',
  EdgeRapid = 'edge-rapid',
  EdgeSlotProp = 'edge-slot-prop',
  EdgeItemSlot = 'edge-item-slot',
  EdgeChannel = 'edge-channel',
  EdgeRemoteAttr = 'edge-remote-attr',
  IntTriggerClick = 'int-trigger-click',
  IntTriggerToggle = 'int-trigger-toggle',
  IntTriggerActive = 'int-trigger-active',
  IntItemHover = 'int-item-hover',
  IntItemLeave = 'int-item-leave',
  IntItemClick = 'int-item-click',
  IntItemDisabled = 'int-item-disabled',
  IntContext = 'int-context',
  IntEscape = 'int-escape',
  KbEscape = 'kb-escape',
  KbEscapeAttr = 'kb-escape-attr',
  KbEnter = 'kb-enter',
  KbTab = 'kb-tab',
  OptDropdown = 'opt-dropdown',
  OptMenubar = 'opt-menubar',
  OptContext = 'opt-context',
  OptNav = 'opt-nav',
  OptTeleportDisabled = 'opt-teleport-disabled',
  OptPlacement = 'opt-placement',
  RenderDataId = 'render-data-id',
  RenderTriggerActive = 'render-trigger-active',
  RenderTriggerDisabled = 'render-trigger-disabled',
  RenderTriggerTab = 'render-trigger-tab',
  RenderTriggerSlot = 'render-trigger-slot',
  RenderViewId = 'render-view-id',
  RenderContentClosed = 'render-content-closed',
  RenderContentOpen = 'render-content-open',
  RenderContentId = 'render-content-id',
  RenderContentInner = 'render-content-inner',
  RenderItem = 'render-item',
  RenderItemActive = 'render-item-active',
  RenderItemDisabled = 'render-item-disabled',
  RenderItemSlot = 'render-item-slot',
  RenderFloat = 'render-float',
  RenderDisabledTrigger = 'render-disabled-trigger',
}

export enum ViewId {
  V0 = 'v0',
  V1 = 'v1',
  RenderV0 = 'view-0',
}

export enum ItemId {
  Item1 = 'item-1',
  Item2 = 'item-2',
  Item3 = 'item-3',
  ParentItem = 'parent-item',
  SubItem = 'sub-item',
  SlotItem = 'slot-item',
  KbItem1 = 'kb-item-1',
  KbItem2 = 'kb-item-2',
  KbItem3 = 'kb-item-3',
}

export enum TestId {
  Trigger = 'trigger',
  Open = 'open',
  Close = 'close',
  Item = 'item',
  RemoteA = 'remote-a',
  ChannelA = 'channel-a',
  SubTrigger = 'sub-trigger',
  Parent = 'parent',
  Toggle = 'toggle',
  Trigger1 = 'trigger-1',
  Trigger2 = 'trigger-2',
  ItemM1 = 'item-m1',
  ItemM2 = 'item-m2',
  Remote1 = 'remote-1',
  ChannelContent = 'channel-content',
  ActiveState = 'active-state',
  ItemActive = 'item-active',
  Area = 'area',
  Item1 = 'item-1',
  Item2 = 'item-2',
  Item3 = 'item-3',
  SubItem = 'sub-item',
}
